name: jimseven
favicon: null
layout_spectrum: 0.6077794299926609
typography_spectrum: 0.10749743692576885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b333f'
    - '#dee8e7'
    - '#c5b9a1'
    - '#789eb3'
    - '#866965'
  brandStrength: 0.9258988474030048
  lightness: 0.33551083598285913
  saturation: 0.5323276079725474
  rhythmicContrast: 0.4333794293925166
purpose: []
